//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFoodOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItems()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int menuitemid { get; set; }
        public string itemname { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public int restaurentid { get; set; }
        public int FoodCategoryID { get; set; }
        public int MainFoodCategoryID { get; set; }
        public string itempic { get; set; }
    
        public virtual MainFoodType MainFoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
