//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFoodOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderid { get; set; }
        public int OrderByUser { get; set; }
        public int RestaurentID { get; set; }
        public int MenuItemID { get; set; }
        public Nullable<int> price { get; set; }
        public string orderdate { get; set; }
        public string session { get; set; }
        public bool paymentdone { get; set; }
        public bool finalorder { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
        public virtual RestaurentRegistration RestaurentRegistration { get; set; }
        public virtual User User { get; set; }
    }
}
