//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFoodOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurentRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurentRegistration()
        {
            this.FoodCategory = new HashSet<FoodCategory>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int RestaurentId { get; set; }
        public string RestaurentEmail { get; set; }
        public Nullable<bool> emailvarified { get; set; }
        public int RestaurentCategory { get; set; }
        public string address { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Regdate { get; set; }
        public System.Guid guid { get; set; }
        public string password { get; set; }
        public string RestaurentName { get; set; }
        public string confirmpassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodCategory> FoodCategory { get; set; }
        public virtual MainFoodType MainFoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
