//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantFoodOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int userid { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> userfoodpreference { get; set; }
        public Nullable<bool> emailvarified { get; set; }
        public string regdate { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<long> mobile { get; set; }
        public string confirmpassword { get; set; }
    
        public virtual MainFoodType MainFoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
